cursor #eceff4
cursor_text_color #eceff4

foreground            #eceff4
background            #2e3440
selection_foreground  #2e3440
selection_background  #b48ead
url_color             #81a1c1

color0   #3b4252
color1   #cc3335
color2   #72d66e
color3   #dbd07b
color4   #38638e
color5   #6a7d90
color6   #81a1c1
color7   #abb2bf
color8   #5c6370
color9   #e05f60
color10  #88e086
color11  #e8df97
color12  #acd9ff
color13  #2e5d73
color14  #35496a
color15  #ffffff
