tab_bar_edge            bottom 
tab_bar_style           powerline 
tab_powerline_style     slanted
tab_bar_align           right 
tab_bar_min_tabs        1
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 0
background_blur 10


active_tab_font_style           bold

inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [♥{index}●]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [♥{index}■]"
